import product1 from "../../assets/images/banner2.jpg";
import product2 from "../../assets/images/banner3.jpg";
import product3 from "../../assets/images/banner4.jpg";
import product4 from "../../assets/images/banner5.jpg";
import product5 from "../../assets/images/banner6.jpg";
import product6 from "../../assets/images/banner7.jpg";

const Products = [
  {
    id: 1,
    brand: "Aurora Fashion",
    title: "Clothing For Women",
    src: product1,
    images: [product1, product1, product1, product1],
    badge: "28%",
    status: "In Stock",
    rating: 5,
    orderNo: "ORD-1001",
    oldPrice: "$20.00",
    netPrice: "$14.00",
    category: "Women’s Apparel",
    tags: ["summer", "style", "trendy"],
    type: "Casual Wear",
    mfgDate: "2026-03-12",
    life: "30 days",
    description:
      "A stylish women’s clothing item with a comfortable fit and modern design.",
  },
  {
    id: 2,
    brand: "Titan Style",
    title: "Clothing For Men",
    src: product2,
    images: [product2, product2, product2, product2],
    badge: "20%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1002",
    oldPrice: "$20.00",
    netPrice: "$14.00",
    category: "Men’s Apparel",
    tags: ["formal", "classic", "new"],
    type: "Formal Wear",
    mfgDate: "2026-02-01",
    life: "30 days",
    description:
      "A premium men’s outfit designed for everyday comfort and sharp style.",
  },
  {
    id: 3,
    brand: "Kids Trend",
    title: "Clothing For Kids",
    src: product3,
    images: [product3, product3, product3, product3],
    badge: "15%",
    status: "Out of Stock",
    rating: 4,
    orderNo: "ORD-1003",
    oldPrice: "$20.00",
    netPrice: "$14.00",
    category: "Kids Apparel",
    tags: ["cute", "play", "comfortable"],
    type: "Everyday Wear",
    mfgDate: "2026-01-20",
    life: "30 days",
    description:
      "A cute and durable kids’ clothing pick that is soft and easy to wear.",
  },
  {
    id: 4,
    brand: "Signature Suits",
    title: "Suits For Men",
    src: product4,
    images: [product4, product4, product4, product4],
    badge: "15%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1004",
    oldPrice: "$250.00",
    netPrice: "$194.00",
    category: "Men’s Formal",
    tags: ["business", "elite", "premium"],
    type: "Formal Suit",
    mfgDate: "2026-01-05",
    life: "30 days",
    description:
      "A sophisticated men’s suit for formal occasions with a sharp finish.",
  },
  {
    id: 5,
    brand: "Elite Watches",
    title: "Rolex",
    src: product5,
    images: [product5, product5, product5, product5],
    badge: "5%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1005",
    oldPrice: "$95,000.00",
    netPrice: "$90,000.00",
    category: "Luxury Accessories",
    tags: ["premium", "luxury", "watch"],
    type: "Luxury Watch",
    mfgDate: "2025-12-11",
    life: "30 days",
    description: "A luxury timepiece with exceptional craftsmanship and style.",
  },
  {
    id: 6,
    brand: "Future Tech",
    title: "Iphone 17 Pro Max",
    src: product6,
    images: [product6, product6, product6, product6],
    badge: "10%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1006",
    oldPrice: "$1,420.00",
    netPrice: "$1,200.00",
    category: "Electronics",
    tags: ["smartphone", "premium", "latest"],
    type: "Mobile Phone",
    mfgDate: "2026-04-01",
    life: "30 days",
    description:
      "The latest premium smartphone with advanced features and sleek design.",
  },

  // 34 additional unique products (reusing existing image assets)
  {
    id: 7,
    brand: "Velvet Aura",
    title: "Women’s Linen Shirt",
    src: product1,
    images: [product1, product2, product1, product3],
    badge: "18%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1007",
    oldPrice: "$38.00",
    netPrice: "$31.00",
    category: "Women’s Apparel",
    tags: ["linen", "breathable", "workwear"],
    type: "Shirt",
    mfgDate: "2026-02-18",
    life: "30 days",
    description:
      "Lightweight linen shirt tailored for comfort and effortless everyday elegance.",
  },
  {
    id: 8,
    brand: "Northern Thread",
    title: "Men’s Thermal Hoodie",
    src: product2,
    images: [product2, product4, product2, product6],
    badge: "25%",
    status: "In Stock",
    rating: 5,
    orderNo: "ORD-1008",
    oldPrice: "$60.00",
    netPrice: "$45.00",
    category: "Men’s Apparel",
    tags: ["thermal", "cozy", "hoodie"],
    type: "Casual Wear",
    mfgDate: "2026-01-28",
    life: "30 days",
    description:
      "Warm and durable hoodie built for chilly mornings and active days.",
  },
  {
    id: 9,
    brand: "PlayNest",
    title: "Kids Graphic Tee",
    src: product3,
    images: [product3, product1, product3, product5],
    badge: "12%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1009",
    oldPrice: "$18.00",
    netPrice: "$15.80",
    category: "Kids Apparel",
    tags: ["graphic", "soft", "daily"],
    type: "T-Shirt",
    mfgDate: "2026-03-02",
    life: "30 days",
    description:
      "A soft kids’ graphic tee designed for comfort through playtime.",
  },
  {
    id: 10,
    brand: "Boardroom",
    title: "Men’s Wool Blazer",
    src: product4,
    images: [product4, product2, product4, product1],
    badge: "22%",
    status: "In Stock",
    rating: 5,
    orderNo: "ORD-1010",
    oldPrice: "$220.00",
    netPrice: "$171.60",
    category: "Men’s Formal",
    tags: ["wool", "business", "tailored"],
    type: "Blazer",
    mfgDate: "2026-01-10",
    life: "30 days",
    description:
      "A tailored wool blazer with premium structure for professional style.",
  },
  {
    id: 11,
    brand: "Chronos Elite",
    title: "Executive Steel Watch",
    src: product5,
    images: [product5, product6, product5, product4],
    badge: "7%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1011",
    oldPrice: "$5,900.00",
    netPrice: "$5,487.00",
    category: "Luxury Accessories",
    tags: ["steel", "classic", "timepiece"],
    type: "Watch",
    mfgDate: "2025-11-20",
    life: "30 days",
    description:
      "A refined steel watch for executive wear and everyday luxury.",
  },
  {
    id: 12,
    brand: "Future Tech",
    title: "IPhone 17 Pro",
    src: product6,
    images: [product6, product3, product6, product2],
    badge: "9%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1012",
    oldPrice: "$1,250.00",
    netPrice: "$1,135.00",
    category: "Electronics",
    tags: ["smartphone", "pro", "fast"],
    type: "Mobile Phone",
    mfgDate: "2026-04-05",
    life: "30 days",
    description:
      "Pro-grade performance with a premium display and advanced camera system.",
  },
  {
    id: 13,
    brand: "Saffron Stitch",
    title: "Women’s Maxi Dress",
    src: product1,
    images: [product2, product1, product3, product1],
    badge: "30%",
    status: "In Stock",
    rating: 5,
    orderNo: "ORD-1013",
    oldPrice: "$75.00",
    netPrice: "$52.50",
    category: "Women’s Apparel",
    tags: ["maxi", "evening", "flowy"],
    type: "Dress",
    mfgDate: "2026-02-22",
    life: "30 days",
    description:
      "A flowy maxi dress crafted to flatter and elevate your evening look.",
  },
  {
    id: 14,
    brand: "Summit Sports",
    title: "Men’s Track Pants",
    src: product2,
    images: [product4, product2, product6, product2],
    badge: "16%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1014",
    oldPrice: "$45.00",
    netPrice: "$37.80",
    category: "Men’s Apparel",
    tags: ["track", "stretch", "training"],
    type: "Active Wear",
    mfgDate: "2026-03-01",
    life: "30 days",
    description:
      "Breathable track pants with stretch comfort for training sessions.",
  },
  {
    id: 15,
    brand: "Little Loom",
    title: "Kids Soft Joggers",
    src: product3,
    images: [product3, product5, product3, product1],
    badge: "14%",
    status: "Out of Stock",
    rating: 4,
    orderNo: "ORD-1015",
    oldPrice: "$22.00",
    netPrice: "$18.92",
    category: "Kids Apparel",
    tags: ["joggers", "soft", "everyday"],
    type: "Jogger",
    mfgDate: "2026-01-15",
    life: "30 days",
    description: "Comfort-first joggers for everyday play with a soft feel.",
  },
  {
    id: 16,
    brand: "Royal Tailor",
    title: "Men’s Formal Shirt",
    src: product4,
    images: [product4, product6, product4, product2],
    badge: "20%",
    status: "In Stock",
    rating: 5,
    orderNo: "ORD-1016",
    oldPrice: "$55.00",
    netPrice: "$44.00",
    category: "Men’s Formal",
    tags: ["formal", "cotton", "sharp"],
    type: "Shirt",
    mfgDate: "2026-02-10",
    life: "30 days",
    description: "Crisp formal shirt made to keep its shape and look polished.",
  },
  {
    id: 17,
    brand: "Aurum Watch Co",
    title: "Gold Tone Dress Watch",
    src: product5,
    images: [product5, product1, product5, product6],
    badge: "8%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1017",
    oldPrice: "$2,400.00",
    netPrice: "$2,208.00",
    category: "Luxury Accessories",
    tags: ["gold", "dress", "sparkle"],
    type: "Watch",
    mfgDate: "2025-12-01",
    life: "30 days",
    description:
      "A gold tone dress watch with a clean dial and premium finish.",
  },
  {
    id: 18,
    brand: "Future Tech",
    title: "Galaxy Flip S",
    src: product6,
    images: [product6, product4, product6, product2],
    badge: "11%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1018",
    oldPrice: "$980.00",
    netPrice: "$872.20",
    category: "Electronics",
    tags: ["foldable", "smart", "sleek"],
    type: "Mobile Phone",
    mfgDate: "2026-03-20",
    life: "30 days",
    description:
      "A foldable smartphone designed for multitasking and portability.",
  },

  {
    id: 19,
    brand: "Bloom & Co",
    title: "Women’s Floral Blouse",
    src: product1,
    images: [product1, product3, product1, product2],
    badge: "24%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1019",
    oldPrice: "$32.00",
    netPrice: "$24.20",
    category: "Women’s Apparel",
    tags: ["floral", "soft", "spring"],
    type: "Blouse",
    mfgDate: "2026-03-05",
    life: "30 days",
    description:
      "Floral blouse with a breathable fabric and a flattering silhouette.",
  },
  {
    id: 20,
    brand: "Cedar & Stone",
    title: "Men’s Oxford Button Down",
    src: product2,
    images: [product2, product1, product4, product2],
    badge: "19%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1020",
    oldPrice: "$58.00",
    netPrice: "$46.98",
    category: "Men’s Apparel",
    tags: ["oxford", "button-down", "classic"],
    type: "Shirt",
    mfgDate: "2026-02-12",
    life: "30 days",
    description:
      "Oxford button-down shirt crafted for a timeless look and comfort.",
  },
  {
    id: 21,
    brand: "Tiny Titan",
    title: "Kids Hoodie Zip",
    src: product3,
    images: [product3, product6, product3, product5],
    badge: "10%",
    status: "In Stock",
    rating: 5,
    orderNo: "ORD-1021",
    oldPrice: "$28.00",
    netPrice: "$25.20",
    category: "Kids Apparel",
    tags: ["zip", "warm", "hoodie"],
    type: "Hoodie",
    mfgDate: "2026-01-30",
    life: "30 days",
    description:
      "A zip-up kids hoodie with cozy warmth and smooth daily comfort.",
  },
  {
    id: 22,
    brand: "Elite Formal",
    title: "Men’s Satin Tie",
    src: product4,
    images: [product4, product2, product4, product1],
    badge: "35%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1022",
    oldPrice: "$25.00",
    netPrice: "$16.25",
    category: "Men’s Formal",
    tags: ["tie", "satin", "event"],
    type: "Necktie",
    mfgDate: "2026-02-25",
    life: "30 days",
    description:
      "Premium satin necktie with a refined sheen for formal occasions.",
  },
  {
    id: 23,
    brand: "Noir Chrono",
    title: "Black Dial Watch",
    src: product5,
    images: [product5, product4, product5, product2],
    badge: "6%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1023",
    oldPrice: "$1,750.00",
    netPrice: "$1,645.50",
    category: "Luxury Accessories",
    tags: ["black", "dial", "sleek"],
    type: "Watch",
    mfgDate: "2025-12-18",
    life: "30 days",
    description: "Minimal black dial watch with a bold, modern look.",
  },
  {
    id: 24,
    brand: "Nova Wireless",
    title: "Wireless Earbuds Pro",
    src: product6,
    images: [product6, product3, product6, product1],
    badge: "15%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1024",
    oldPrice: "$120.00",
    netPrice: "$102.00",
    category: "Electronics",
    tags: ["earbuds", "wireless", "noise-cancel"],
    type: "Audio",
    mfgDate: "2026-03-18",
    life: "30 days",
    description: "Comfortable wireless earbuds with active noise cancellation.",
  },

  {
    id: 25,
    brand: "Luna Knit",
    title: "Women’s Ribbed Sweater",
    src: product1,
    images: [product1, product2, product1, product4],
    badge: "27%",
    status: "In Stock",
    rating: 5,
    orderNo: "ORD-1025",
    oldPrice: "$90.00",
    netPrice: "$65.70",
    category: "Women’s Apparel",
    tags: ["ribbed", "warm", "knit"],
    type: "Sweater",
    mfgDate: "2026-01-22",
    life: "30 days",
    description: "Ribbed knit sweater with a soft feel and a flattering fit.",
  },
  {
    id: 26,
    brand: "Iron & Ink",
    title: "Men’s Graphic T-Shirt",
    src: product2,
    images: [product2, product5, product2, product3],
    badge: "13%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1026",
    oldPrice: "$24.00",
    netPrice: "$20.88",
    category: "Men’s Apparel",
    tags: ["graphic", "cotton", "street"],
    type: "T-Shirt",
    mfgDate: "2026-02-08",
    life: "30 days",
    description: "Cotton graphic tee designed for a clean streetwear look.",
  },
  {
    id: 27,
    brand: "Sprout Wear",
    title: "Kids Colorblock Shorts",
    src: product3,
    images: [product3, product2, product3, product6],
    badge: "17%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1027",
    oldPrice: "$19.00",
    netPrice: "$15.73",
    category: "Kids Apparel",
    tags: ["colorblock", "summer", "play"],
    type: "Shorts",
    mfgDate: "2026-03-10",
    life: "30 days",
    description: "Breathable shorts with vibrant colorblocking for summer fun.",
  },
  {
    id: 28,
    brand: "Prime Suits",
    title: "Men’s Checkered Blazer",
    src: product4,
    images: [product4, product1, product4, product2],
    badge: "21%",
    status: "Out of Stock",
    rating: 4,
    orderNo: "ORD-1028",
    oldPrice: "$240.00",
    netPrice: "$189.60",
    category: "Men’s Formal",
    tags: ["checkered", "premium", "event"],
    type: "Blazer",
    mfgDate: "2026-01-12",
    life: "30 days",
    description:
      "Checkered blazer made for modern formal events and standout style.",
  },
  {
    id: 29,
    brand: "Vanta Watch",
    title: "Vanta Chronograph",
    src: product5,
    images: [product5, product6, product5, product3],
    badge: "9%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1029",
    oldPrice: "$3,200.00",
    netPrice: "$2,912.00",
    category: "Luxury Accessories",
    tags: ["chronograph", "sport", "luxury"],
    type: "Chronograph",
    mfgDate: "2025-11-30",
    life: "30 days",
    description:
      "A chronograph watch with refined detailing and sport-lux styling.",
  },
  {
    id: 30,
    brand: "Future Tech",
    title: "Smartwatch S2",
    src: product6,
    images: [product6, product4, product6, product5],
    badge: "13%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1030",
    oldPrice: "$180.00",
    netPrice: "$156.60",
    category: "Electronics",
    tags: ["watch", "health", "smart"],
    type: "Smartwatch",
    mfgDate: "2026-02-28",
    life: "30 days",
    description:
      "Track health metrics and notifications with an easy-to-use smartwatch.",
  },

  {
    id: 31,
    brand: "Velvet Aura",
    title: "Women’s Satin Skirt",
    src: product1,
    images: [product1, product5, product1, product2],
    badge: "23%",
    status: "In Stock",
    rating: 5,
    orderNo: "ORD-1031",
    oldPrice: "$70.00",
    netPrice: "$53.90",
    category: "Women’s Apparel",
    tags: ["satin", "party", "silky"],
    type: "Skirt",
    mfgDate: "2026-03-08",
    life: "30 days",
    description:
      "Satin skirt with a smooth drape for dressy occasions and nights out.",
  },
  {
    id: 32,
    brand: "Cedar & Stone",
    title: "Men’s Stretch Chinos",
    src: product2,
    images: [product2, product1, product2, product4],
    badge: "18%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1032",
    oldPrice: "$62.00",
    netPrice: "$50.84",
    category: "Men’s Apparel",
    tags: ["chinos", "stretch", "everyday"],
    type: "Chino",
    mfgDate: "2026-02-16",
    life: "30 days",
    description:
      "Stretch chinos with a comfortable waistband and clean everyday fit.",
  },
  {
    id: 33,
    brand: "Little Loom",
    title: "Kids Adventure Cap",
    src: product3,
    images: [product3, product6, product3, product2],
    badge: "11%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1033",
    oldPrice: "$16.00",
    netPrice: "$14.24",
    category: "Kids Apparel",
    tags: ["cap", "adventure", "sun"],
    type: "Hat",
    mfgDate: "2026-03-03",
    life: "30 days",
    description:
      "An adventure cap built for sunny days and comfortable playtime.",
  },
  {
    id: 34,
    brand: "Royal Tailor",
    title: "Men’s Formal Pocket Square",
    src: product4,
    images: [product4, product1, product4, product6],
    badge: "28%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1034",
    oldPrice: "$30.00",
    netPrice: "$21.60",
    category: "Men’s Formal",
    tags: ["pocket", "classic", "wedding"],
    type: "Accessories",
    mfgDate: "2026-02-20",
    life: "30 days",
    description:
      "A crisp pocket square that adds detail and polish to formal looks.",
  },
  {
    id: 35,
    brand: "Chronos Elite",
    title: "Silver Leather Watch",
    src: product5,
    images: [product5, product2, product5, product1],
    badge: "10%",
    status: "Out of Stock",
    rating: 4,
    orderNo: "ORD-1035",
    oldPrice: "$900.00",
    netPrice: "$810.00",
    category: "Luxury Accessories",
    tags: ["leather", "silver", "classic"],
    type: "Watch",
    mfgDate: "2025-12-05",
    life: "30 days",
    description:
      "Silver watch with leather strap for a timeless, elevated appearance.",
  },
  {
    id: 36,
    brand: "Nova Wireless",
    title: "Portable Power Bank 20K",
    src: product6,
    images: [product6, product3, product6, product2],
    badge: "16%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1036",
    oldPrice: "$65.00",
    netPrice: "$54.60",
    category: "Electronics",
    tags: ["powerbank", "portable", "fast-charge"],
    type: "Accessory",
    mfgDate: "2026-03-14",
    life: "30 days",
    description:
      "High-capacity power bank with reliable output for on-the-go charging.",
  },

  {
    id: 37,
    brand: "Saffron Stitch",
    title: "Women’s Wrap Dress",
    src: product1,
    images: [product1, product2, product1, product3],
    badge: "29%",
    status: "In Stock",
    rating: 5,
    orderNo: "ORD-1037",
    oldPrice: "$82.00",
    netPrice: "$58.22",
    category: "Women’s Apparel",
    tags: ["wrap", "flattering", "summer"],
    type: "Dress",
    mfgDate: "2026-02-26",
    life: "30 days",
    description:
      "Wrap dress designed to enhance your silhouette with a comfortable tie fit.",
  },
  {
    id: 38,
    brand: "Iron & Ink",
    title: "Men’s Polo Classic",
    src: product2,
    images: [product2, product4, product2, product6],
    badge: "17%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1038",
    oldPrice: "$40.00",
    netPrice: "$33.20",
    category: "Men’s Apparel",
    tags: ["polo", "breathable", "classic"],
    type: "Polo",
    mfgDate: "2026-03-07",
    life: "30 days",
    description:
      "Classic polo with breathable fabric for comfortable everyday wear.",
  },
  {
    id: 39,
    brand: "Sprout Wear",
    title: "Kids Denim Jacket",
    src: product3,
    images: [product3, product1, product3, product4],
    badge: "21%",
    status: "In Stock",
    rating: 4,
    orderNo: "ORD-1039",
    oldPrice: "$55.00",
    netPrice: "$43.45",
    category: "Kids Apparel",
    tags: ["denim", "jacket", "layers"],
    type: "Jacket",
    mfgDate: "2026-01-25",
    life: "30 days",
    description:
      "Kids denim jacket with sturdy stitching and comfortable layering.",
  },
  {
    id: 40,
    brand: "Prime Suits",
    title: "Men’s Leather Belt",
    src: product4,
    images: [product4, product5, product4, product2],
    badge: "24%",
    status: "In Stock",
    rating: 5,
    orderNo: "ORD-1040",
    oldPrice: "$48.00",
    netPrice: "$36.48",
    category: "Men’s Formal",
    tags: ["leather", "belt", "premium"],
    type: "Belt",
    mfgDate: "2026-02-02",
    life: "30 days",
    description:
      "Premium leather belt with a polished buckle for formal outfits.",
  },
];

export default Products;
